name: Manual Trigger Workflow

# Controls when the action will run
on:
  workflow_dispatch:  # This makes the workflow run manually

jobs:
  run-manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run a script
        run: echo "This is a manually triggered workflow."
