name: Automated + Manual Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  automated_step:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run automated tasks
        run: |
          echo "Running automated task"
          # Add your automated commands here

  # Step 2: Manual Approval (skipped if triggered by workflow_dispatch)
  manual_approval:
    runs-on: ubuntu-latest
    needs: automated_step
    if: github.event_name != 'workflow_dispatch'  # Skip for manual triggers
    steps:
      - name: Wait for approval
        run: echo "Waiting for manual approval"
      
      - name: Request Manual Approval
        uses: actions/github-script@v6
        with:
          script: |
            const comment = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number, # Reference the current PR or Issue number
              body: 'Please approve this workflow manually by adding an approval comment.'
            })
            console.log(comment)

  # Step 3: Manual Step
  manual_step:
    runs-on: ubuntu-latest
    needs: [automated_step, manual_approval]  # Depends on both steps
    if: github.event_name == 'workflow_dispatch'  # Run if manually triggered or approved
    steps:
      - name: Perform manual task
        run: |
          echo "Executing the manual task after approval"
          # Add your manual commands here
